
//------------------------------------------------------------------------------

//  <auto-generated>
//      This code was generated by:
//        TerminalGuiDesigner v1.0.24.0
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// -----------------------------------------------------------------------------
namespace AntennaSwitch {
    using System;
    using Terminal.Gui;
    
    
    public partial class AntennaSwitchWindow : Terminal.Gui.Toplevel {
        
        private Terminal.Gui.ColorScheme blueOnBlack;
        
        private Terminal.Gui.ColorScheme scheme;
        
        private Terminal.Gui.ColorScheme greenOnBlack;
        
        private Terminal.Gui.FrameView antennaSwitchFrameView;
        
        private Terminal.Gui.Label frequencyLabel;
        
        private Terminal.Gui.Label frequencyValueLabel;
        
        private Terminal.Gui.Label currentAntennaLabel;
        
        private Terminal.Gui.Label currentAntennaValueLabel;
        
        private Terminal.Gui.Label bandLabel;
        
        private Terminal.Gui.Label bandValueLabel;
        
        private Terminal.Gui.Label wantedAntennaLabel;
        
        private Terminal.Gui.Label wantedAntennaValueLabel;
        
        private Terminal.Gui.CheckBox supportsBandCheckBox;
        
        private Terminal.Gui.Label comPortLabel;
        
        private Terminal.Gui.Label comPortValueLabel;
        
        private void InitializeComponent() {
            this.comPortValueLabel = new Terminal.Gui.Label();
            this.comPortLabel = new Terminal.Gui.Label();
            this.supportsBandCheckBox = new Terminal.Gui.CheckBox();
            this.wantedAntennaValueLabel = new Terminal.Gui.Label();
            this.wantedAntennaLabel = new Terminal.Gui.Label();
            this.bandValueLabel = new Terminal.Gui.Label();
            this.bandLabel = new Terminal.Gui.Label();
            this.currentAntennaValueLabel = new Terminal.Gui.Label();
            this.currentAntennaLabel = new Terminal.Gui.Label();
            this.frequencyValueLabel = new Terminal.Gui.Label();
            this.frequencyLabel = new Terminal.Gui.Label();
            this.antennaSwitchFrameView = new Terminal.Gui.FrameView();
            this.blueOnBlack = new Terminal.Gui.ColorScheme();
            this.blueOnBlack.Normal = new Terminal.Gui.Attribute(Terminal.Gui.Color.BrightBlue, Terminal.Gui.Color.Black);
            this.blueOnBlack.HotNormal = new Terminal.Gui.Attribute(Terminal.Gui.Color.Cyan, Terminal.Gui.Color.Black);
            this.blueOnBlack.Focus = new Terminal.Gui.Attribute(Terminal.Gui.Color.BrightBlue, Terminal.Gui.Color.BrightYellow);
            this.blueOnBlack.HotFocus = new Terminal.Gui.Attribute(Terminal.Gui.Color.Cyan, Terminal.Gui.Color.BrightYellow);
            this.blueOnBlack.Disabled = new Terminal.Gui.Attribute(Terminal.Gui.Color.Gray, Terminal.Gui.Color.Black);
            this.scheme = new Terminal.Gui.ColorScheme();
            this.scheme.Normal = new Terminal.Gui.Attribute(Terminal.Gui.Color.White, Terminal.Gui.Color.Black);
            this.scheme.HotNormal = new Terminal.Gui.Attribute(Terminal.Gui.Color.White, Terminal.Gui.Color.Black);
            this.scheme.Focus = new Terminal.Gui.Attribute(Terminal.Gui.Color.White, Terminal.Gui.Color.Black);
            this.scheme.HotFocus = new Terminal.Gui.Attribute(Terminal.Gui.Color.White, Terminal.Gui.Color.Black);
            this.scheme.Disabled = new Terminal.Gui.Attribute(Terminal.Gui.Color.White, Terminal.Gui.Color.Black);
            this.greenOnBlack = new Terminal.Gui.ColorScheme();
            this.greenOnBlack.Normal = new Terminal.Gui.Attribute(Terminal.Gui.Color.Green, Terminal.Gui.Color.Black);
            this.greenOnBlack.HotNormal = new Terminal.Gui.Attribute(Terminal.Gui.Color.BrightGreen, Terminal.Gui.Color.Black);
            this.greenOnBlack.Focus = new Terminal.Gui.Attribute(Terminal.Gui.Color.Green, Terminal.Gui.Color.Magenta);
            this.greenOnBlack.HotFocus = new Terminal.Gui.Attribute(Terminal.Gui.Color.BrightGreen, Terminal.Gui.Color.Magenta);
            this.greenOnBlack.Disabled = new Terminal.Gui.Attribute(Terminal.Gui.Color.Gray, Terminal.Gui.Color.Black);
            this.Width = Dim.Fill(0);
            this.Height = Dim.Fill(0);
            this.X = 0;
            this.Y = 0;
            this.Modal = false;
            this.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.antennaSwitchFrameView.Width = 47;
            this.antennaSwitchFrameView.Height = 6;
            this.antennaSwitchFrameView.X = 0;
            this.antennaSwitchFrameView.Y = 0;
            this.antennaSwitchFrameView.ColorScheme = this.greenOnBlack;
            this.antennaSwitchFrameView.Data = "antennaSwitchFrameView";
            this.antennaSwitchFrameView.Border.BorderStyle = Terminal.Gui.BorderStyle.Single;
            this.antennaSwitchFrameView.Border.BorderBrush = Terminal.Gui.Color.Green;
            this.antennaSwitchFrameView.Border.Effect3D = false;
            this.antennaSwitchFrameView.Border.Effect3DBrush = null;
            this.antennaSwitchFrameView.Border.DrawMarginFrame = true;
            this.antennaSwitchFrameView.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.antennaSwitchFrameView.Title = "Antenna Switch";
            this.Add(this.antennaSwitchFrameView);
            this.frequencyLabel.Width = 11;
            this.frequencyLabel.Height = 1;
            this.frequencyLabel.X = 1;
            this.frequencyLabel.Y = 1;
            this.frequencyLabel.ColorScheme = this.scheme;
            this.frequencyLabel.Data = "frequencyLabel";
            this.frequencyLabel.Text = "Frequency:";
            this.frequencyLabel.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.antennaSwitchFrameView.Add(this.frequencyLabel);
            this.frequencyValueLabel.Width = 8;
            this.frequencyValueLabel.Height = 1;
            this.frequencyValueLabel.X = 12;
            this.frequencyValueLabel.Y = 1;
            this.frequencyValueLabel.ColorScheme = this.scheme;
            this.frequencyValueLabel.Data = "frequencyValueLabel";
            this.frequencyValueLabel.Text = "24915000";
            this.frequencyValueLabel.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.antennaSwitchFrameView.Add(this.frequencyValueLabel);
            this.currentAntennaLabel.Width = 4;
            this.currentAntennaLabel.Height = 1;
            this.currentAntennaLabel.X = 25;
            this.currentAntennaLabel.Y = 1;
            this.currentAntennaLabel.ColorScheme = this.scheme;
            this.currentAntennaLabel.Data = "currentAntennaLabel";
            this.currentAntennaLabel.Text = "Current:";
            this.currentAntennaLabel.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.antennaSwitchFrameView.Add(this.currentAntennaLabel);
            this.currentAntennaValueLabel.Width = 4;
            this.currentAntennaValueLabel.Height = 1;
            this.currentAntennaValueLabel.X = 36;
            this.currentAntennaValueLabel.Y = 1;
            this.currentAntennaValueLabel.ColorScheme = this.scheme;
            this.currentAntennaValueLabel.Data = "currentAntennaValueLabel";
            this.currentAntennaValueLabel.Text = "Dipole";
            this.currentAntennaValueLabel.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.antennaSwitchFrameView.Add(this.currentAntennaValueLabel);
            this.bandLabel.Width = 4;
            this.bandLabel.Height = 1;
            this.bandLabel.X = 1;
            this.bandLabel.Y = 2;
            this.bandLabel.ColorScheme = this.scheme;
            this.bandLabel.Data = "bandLabel";
            this.bandLabel.Text = "Band:";
            this.bandLabel.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.antennaSwitchFrameView.Add(this.bandLabel);
            this.bandValueLabel.Width = 4;
            this.bandValueLabel.Height = 1;
            this.bandValueLabel.X = 12;
            this.bandValueLabel.Y = 2;
            this.bandValueLabel.ColorScheme = this.scheme;
            this.bandValueLabel.Data = "bandValueLabel";
            this.bandValueLabel.Text = "12m";
            this.bandValueLabel.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.antennaSwitchFrameView.Add(this.bandValueLabel);
            this.wantedAntennaLabel.Width = 10;
            this.wantedAntennaLabel.Height = 1;
            this.wantedAntennaLabel.X = 25;
            this.wantedAntennaLabel.Y = 2;
            this.wantedAntennaLabel.ColorScheme = this.scheme;
            this.wantedAntennaLabel.Data = "wantedAntennaLabel";
            this.wantedAntennaLabel.Text = "Wanted:";
            this.wantedAntennaLabel.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.antennaSwitchFrameView.Add(this.wantedAntennaLabel);
            this.wantedAntennaValueLabel.Width = 10;
            this.wantedAntennaValueLabel.Height = 1;
            this.wantedAntennaValueLabel.X = 36;
            this.wantedAntennaValueLabel.Y = 2;
            this.wantedAntennaValueLabel.ColorScheme = this.scheme;
            this.wantedAntennaValueLabel.Data = "wantedAntennaValueLabel";
            this.wantedAntennaValueLabel.Text = "EndFed";
            this.wantedAntennaValueLabel.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.antennaSwitchFrameView.Add(this.wantedAntennaValueLabel);
            this.supportsBandCheckBox.Width = 12;
            this.supportsBandCheckBox.Height = 1;
            this.supportsBandCheckBox.X = 1;
            this.supportsBandCheckBox.Y = 3;
            this.supportsBandCheckBox.ColorScheme = this.scheme;
            this.supportsBandCheckBox.Data = "supportsBandCheckBox";
            this.supportsBandCheckBox.Text = "Supported:";
            this.supportsBandCheckBox.TextAlignment = Terminal.Gui.TextAlignment.Right;
            this.supportsBandCheckBox.Checked = false;
            this.antennaSwitchFrameView.Add(this.supportsBandCheckBox);
            this.comPortLabel.Width = 10;
            this.comPortLabel.Height = 1;
            this.comPortLabel.X = 25;
            this.comPortLabel.Y = 3;
            this.comPortLabel.ColorScheme = this.scheme;
            this.comPortLabel.Data = "comPortLabel";
            this.comPortLabel.Text = "COM Port:";
            this.comPortLabel.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.antennaSwitchFrameView.Add(this.comPortLabel);
            this.comPortValueLabel.Width = 10;
            this.comPortValueLabel.Height = 1;
            this.comPortValueLabel.X = 36;
            this.comPortValueLabel.Y = 3;
            this.comPortValueLabel.ColorScheme = this.scheme;
            this.comPortValueLabel.Data = "comPortValueLabel";
            this.comPortValueLabel.Text = "COM1";
            this.comPortValueLabel.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.antennaSwitchFrameView.Add(this.comPortValueLabel);
        }
    }
}
